language: objective-c
osx_image: xcode8.1

env:
  matrix:
    - TEST_TYPE=iOS
    - TEST_TYPE=OSX

script: 
- |
    if [ "$TEST_TYPE" = iOS ]; then
      xcodebuild clean build -project iOS-Echarts.xcodeproj -target iOS-Echarts_iOS -sdk iphonesimulator10.1 ONLY_ACTIVE_ARCH=NO
    elif [ "$TEST_TYPE" = OSX]; then
      xcodebuild clean build -project iOS-Echarts.xcodeproj -target iOS-Echarts_OSX -sdk macosx
    fi
